### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by zishang520** [tssajo/Minify#45]
```
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\Data\Packages\Minify\Minify.py", line 83, in <lambda>
    sublime.set_timeout_async(lambda: self.do_action(), 0)
  File "D:\Program Files\Sublime Text 3\Data\Packages\Minify\Minify.py", line 201, in do_action
    self.minify()
  File "D:\Program Files\Sublime Text 3\Data\Packages\Minify\Minify.py", line 156, in minify
    self.run_cmd(cmd, outfile)
  File "D:\Program Files\Sublime Text 3\Data\Packages\Minify\Minify.py", line 70, in run_cmd
    self.handle_result(cmd, outfile, retCode, output)
  File "D:\Program Files\Sublime Text 3\Data\Packages\Minify\Minify.py", line 53, in handle_result
    sublime.error_message(' '.join(cmd) + '\r\n\r\n' + output.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 11: invalid start byte
```

**Comment by tssajo** [comment]
@zishang520 Hi, what are you trying to do? Are you trying to minify a file? Is that a javascript or a CSS file? Can you send more info from the console output of SublimeText 3 ? Thanks!

**Comment by tssajo** [comment]
I did some further investigation and it seems to me that whatever you try to do (e.g. minify a file) that did not work and the output from the 3rd party minifier program printed out an error message which is NOT an Unicode message. So there was some sort of an error while the 3rd party program was running and then the 3rd party program gave an error message which cannot be UTF-8 decoded, therefore it cannot be displayed in SublimeText as an error popup message.

I suggest you check your SublimeText console output to find out what command `Minify` is trying to run. Then try to run that exact same command from your command line and see what happens. I'm quiet sure that command will show some sort of an error message.

**Comment by zishang520** [comment]
@tssajo I find the reasons, 7 does not run correctly in windows, but the windows 10 is normal operation, thanks for your answer
--Google translation

**Comment by codeliter** [comment]
I tried beautifying a file and it returned the following error in a console

`Minify: Beautifying file:/var/www/html/html/js/bootstrap.min.js
Traceback (most recent call last):
  File "/home/just_steve/.config/sublime-text-3/Packages/Minify/Minify.py", line 83, in <lambda>
    sublime.set_timeout_async(lambda: self.do_action(), 0)
  File "/home/just_steve/.config/sublime-text-3/Packages/Minify/Minify.py", line 205, in do_action
    self.beautify()
  File "/home/just_steve/.config/sublime-text-3/Packages/Minify/Minify.py", line 197, in beautify
    self.run_cmd(cmd, outfile)
  File "/home/just_steve/.config/sublime-text-3/Packages/Minify/Minify.py", line 69, in run_cmd
    retCode, output = self.runProgram(cmd)
  File "/home/just_steve/.config/sublime-text-3/Packages/Minify/Minify.py", line 26, in runProgram
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=USE_SHELL, env=POPEN_ENV)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'uglifyjs'`

**Comment by zishang520** [comment]
@codeliter You don't Install uglifyjs
please read https://github.com/tssajo/Minify/blob/master/README.md
