### ISSUE TITLE
Minify fails with `class`

### ISSUE THREAD

**Issue by geoidesic** [tssajo/Minify#72]
```
Parse error at /Users/me/.pyenv/versions/3.5.6/envs/roadbuster/lib/python3.5/site-packages/filer/static/filer/js/libs/dropzone.js:32,6
class Emitter {
      ^
ERROR: Unexpected token: name (Emitter)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/me/.nvm/versions/node/v11.2.0/lib/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at fatal (/Users/me/.nvm/versions/node/v11.2.0/lib/node_modules/uglify-js/bin/uglifyjs:291:53)
    at run (/Users/me/.nvm/versions/node/v11.2.0/lib/node_modules/uglify-js/bin/uglifyjs:235:9)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v11.2.0/lib/node_modules/uglify-js/bin/uglifyjs:160:5)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
```
This is the file I was trying to minify:
https://gitlab.com/meno/dropzone/raw/master/src/dropzone.js

**Comment by tssajo** [comment]
@geoidesic It seems to be an issue with the UglifyJS program. Please report the issue to them:
https://github.com/mishoo/UglifyJS2
